from tkinter import *
win=Tk()
win.title("My")
win.iconbitmap('icon.ico')
win.maxsize(width=600,height=300)
win.minsize(width=600,height=300)
def func():
    x= var.get()
    print(x)
    lbl.config(text=x,bg='green')
lbl=Label(win,text="User Name",bg='red',fg='white')
lbl.place(x=10,y=20)
lbl=Label(win,text="Nothing",bg='red',fg='white')
lbl.place(x=80,y=100)
var=StringVar()
ent=Entry(win,bg='red',fg='white',bd=5,textvariable=var)
ent.place(x=80,y=20)
btn=Button(win,text="Submit",bg='green',command=func)
btn.place(x=80,y=60)
win.mainloop()